### PR TITLE
#8688ry8fg institution error messages

### PR DESCRIPTION
**Pull request by lc-hd**
* Removed double periods
* Removed redundant check for uniqueness of name
* modified error message so field name is not displayed

image

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688ry8fg User trying to create Insitution that is already in the Hub error msg](https://app.clickup.com/t/8688ry8fg)

**Comment by birbjam** [comment]
Why does that say "enter a valid URL"? Is it putting all possible errors under that one field?

**Comment by lc-hd** [comment]
> Why does that say "enter a valid URL"? Is it putting all possible errors under that one field?

-----
@birbjam currently, the errors are shown in that position for this form. Here's what that looks like on Develop.

image

**Comment by arojas1** [comment]
I think this might need more discussion because I think what would be best here would be the error bubbles that show on other forms like the img 1 below that indicates there is an error with that field specifically. Or if we can have the error show more precisely for the field it is referencing like img 2, then we can have the field name not show and it would make more sense
image
image

**Review by birbjam — CHANGES_REQUESTED** [review]
Moving this message from Slack:

> To respond to Ashley’s comment:
> The “bubble” type error happens from the frontend template. When an html element has the keyword required  on it. So for example <input type="email" required> , it will say This field is required  without doing anything on the backend yet, while the other error message types are validated in the backend to ensure things like “is it a complete email?“, “is it a valid URL”, etc. is determined.
> 
> To respond to Herbert’s comment:
> We need to make sure that those validation/field errors that appear, appear under each of the fields that are causing the actual error because having them all appear where they do will be confusing for the user.

**Comment by lc-hd** [comment]
This has been updated so the errors are shown below the associated input.

image

**Review by birbjam — APPROVED** [review]
This looks good

**Pull request merged**
