### PR TITLE
#8689anqdv-institution-capitalization-validation

### PR DESCRIPTION
**Pull request by lc-hd**
Error on the custom Institution Name Creation from
image

---

Error in the Admin Panel

image

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8689anqdv Add validation for Custom Institution Account Creation for capitalization](https://app.clickup.com/t/8689anqdv)

**Comment by birbjam** [comment]
Can this error message be changed to what we currently have for unique names so it is more user-friendly?
`This institution is already on the Hub.`

**Review by birbjam — APPROVED** [review]

**Review by arojas1 — CHANGES_REQUESTED** [review]
Not sure if this branch is waiting for code from another push or if it was removed by accident but the error is not coming up for me but the form doesn't submit

**Review by arojas1 — APPROVED** [review]
Thanks! Working well, just if the UI can be updated to match the other error message (website one as example) then that would be best
image

**Pull request merged**
