### PR TITLE
#86886tz8p Address feedback on subscription tickets

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/86886tz8p)**

**Solution:**
- Added another field `is_submitted` to institution table to keep track whether they submitted the subscription form or not
- Setting is_subscribed to True when the response is received from the SF to keep the track whether the institution is subscribed or not.
- Added validation on the admin page so that atleast and only one of the account is selected for the subscription

**Videos:**
The [link](https://drive.google.com/file/d/1OYuT3cM5vHJmniVH-xD2CP_5FGUFljdb/view?usp=sharing) for the video is attached.

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-86886tz8p Address feedback on subscription tickets](https://app.clickup.com/t/86886tz8p)

**Review by arojas1 — CHANGES_REQUESTED** [review]
- disabled-btn should be used in cases where the button should be disabled (re previous dev meeting). The error message should show on hover:
  - Create Project buttons on Notices page and Project page
  - Download Notices
- Add member modal (img 1), role option should only include "Viewer" in the dropdown if they don't have any user count left with a note on how many user counts they have. Same for the Accept request modal (img 2). (will ask for content for these modals)
image
image

- I think for the accepting invites page for users, the Accept invite button should be disabled if the institution account doesn't have user count left and the message I think should just be "The editor and admin limit for this institution as been reached."
image

- When inviting communities, same thing as the member modal above, it should only allow you to add the number of communities based on your count. Once they run out of notifications, the notify communities button should be disabled with the info icon to indicate why
image
image
image

**Review by lc-hd — APPROVED** [review]

**Review by birbjam — CHANGES_REQUESTED** [review]
I just have a few small updates:

- Button UI: When account is not subscribed, the `Create a Project` buttons in the account (on Notices and Projects pages) should not be clickable at all. Remove class `green-btn` and add class `disabled-btn`.

- Re: Ashley's comment about the member roles only showing Viewer:
  - The dropdown should still show all the roles but `Admin` and `Editor` should be disabled.
  - Same for the `Accept a join request` modal.
  - Viewers can still be added to the account regardless of subscription status and user counts.

- `Notify Communities` modal should show how many notifications are left.

**Comment by sab-LC** [comment]
> * disabled-btn should be used in cases where the button should be disabled (re previous dev meeting). The error message should show on hover:
>   
>   * Create Project buttons on Notices page and Project page
>   * Download Notices
> * Add member modal (img 1), role option should only include "Viewer" in the dropdown if they don't have any user count left with a note on how many user counts they have. Same for the Accept request modal (img 2). (will ask for content for these modals)
>   image
>   image
> * I think for the accepting invites page for users, the Accept invite button should be disabled if the institution account doesn't have user count left and the message I think should just be "The editor and admin limit for this institution as been reached."
>   image
> * When inviting communities, same thing as the member modal above, it should only allow you to add the number of communities based on your count. Once they run out of notifications, the notify communities button should be disabled with the info icon to indicate why
>   image
>   image
>   image

The [link](https://drive.google.com/file/d/1T0rmrOayTmbyHAGc6nUsrtnyeXbAfxKx/view?usp=sharing) for the video is attached

**Comment by sab-LC** [comment]
> I just have a few small updates:
> 
> * Button UI: When account is not subscribed, the `Create a Project` buttons in the account (on Notices and Projects pages) should not be clickable at all. Remove class `green-btn` and add class `disabled-btn`.
> * Re: Ashley's comment about the member roles only showing Viewer:
>   
>   * The dropdown should still show all the roles but `Admin` and `Editor` should be disabled.
>   * Same for the `Accept a join request` modal.
>   * Viewers can still be added to the account regardless of subscription status and user counts.
> * `Notify Communities` modal should show how many notifications are left.


https://github.com/localcontexts/localcontextshub/assets/145371882/a460702c-0f7d-4ddb-8929-469a785df3bb

**Comment by birbjam** [comment]
Looking good so far! I wanted to clarify what I mean by this:

> > * Re: Ashley's comment about the member roles only showing Viewer:
> >   
> >   * The dropdown should still show all the roles but `Admin` and `Editor` should be disabled.
> >   * Same for the `Accept a join request` modal.

I think I saw in the videos that there was one dropdown where just the Viewer was available to select and another where all were available. All the roles should show but non-viewers should be greyed out and not selectable. This includes the `Add Member` modal.

Here's an example of what I mean:
h

**Comment by sab-LC** [comment]
> We also just recently changed the UI for hover-over info for disabled buttons from orange to these: Screenshot 2024-04-23 at 10 27 44 AM
> 
> Examples of these can be found in the researcher account.

Screenshot

**Review by birbjam — APPROVED** [review]
There may be some content changes for the counts in the UI that might need to be adjusted but for now it all looks good.

**Pull request merged**
