### PR TITLE
#868b20wa7 issue uploading shapefile

### PR DESCRIPTION
**Pull request by lc-hd**
The issue with the shapefile encountered was due to a mismatch between the array length expected and the length observed. 

This PR does the following: 
* updates the shpjs library to the newest version. 
* And fixes the issue by an empty return when there is an issue creating the DataView

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-868b20wa7 Issue uploading a shapefile](https://app.clickup.com/t/868b20wa7)

**Review by birbjam — CHANGES_REQUESTED** [review]
This did not work for me. 
I went into Settings for my community account and uploaded the file that was shared with us via Zammad/Slack (included in the Task). The file uploaded successfully but when I went to View Location, it showed this:
Screenshot 2024-12-06 at 12 18 47 PM

**Comment by lc-hd** [comment]
> This did not work for me. I went into Settings for my community account and uploaded the file that was shared with us via Zammad/Slack (included in the Task). The file uploaded successfully but when I went to View Location, it showed this: Screenshot 2024-12-06 at 12 18 47 PM

Thanks for finding this issue. It appears to be happening on the Develop branch as well when updating an account. I created another ticket to fix this issue: https://app.clickup.com/t/868b7dfwq

**Review by arojas1 — APPROVED** [review]
tested with other PR to fix issue Diana had and looks good

**Review by sab-LC — APPROVED** [review]

**Pull request merged**
