### PR TITLE
#8685dweqe Notification-for-Notified-Communities

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8685dweqe)**
  
- Description: Currently, if a community has been notified of a Project and that Project gets edited, there is no notification that lets the notified community know that anything has changed on the Project. There should be an action notification in the GUI and possibly an email sent as well.

**Solution:**
- Detected the change in the Edit project form.
- Updated the change flag based on the change in notice or notice translations.
- Get communities based of the status is Labels Pending or Acknowledge Notice.
- Sent ActionNotification to notified communities based on whether the change is detected or not.

**Before:**
notifiedcommunities(before)

**After:**
The [link](https://drive.google.com/file/d/1WrK_-uLoaaU3AbEECpGYjb2ily5D5yJq/view?usp=sharing) for video demo.
actionnotification(after)

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8685dweqe Notification for Notified Communities On Project Edit](https://app.clickup.com/t/8685dweqe)

**Review by lc-hd — APPROVED** [review]

**Comment by arojas1** [comment]
> Functionality looks good, just needs to update the wording of the notification from "Project was customized" to " Edits were made to Project "[truncated Project title]" "

Agreed. Or to match some of the other notifications, "[Account Name] has edited a Project: [Truncated Project Title]"

**Comment by sab-LC** [comment]
> > Functionality looks good, just needs to update the wording of the notification from "Project was customized" to " Edits were made to Project "[truncated Project title]" "
> 
> Agreed. Or to match some of the other notifications, "[Account Name] has edited a Project: [Truncated Project Title]"

ssnotification(after)

**Review by arojas1 — APPROVED** [review]
There just needs to be a space between separating "Project:" and the project name.

Before:
researcher has edited a Project:"Truncated Project Name"

After:
researcher has edited a Project: "Truncated Project Name"

Other than that, looks good!

**Comment by sab-LC** [comment]
> There just needs to be a space between separating "Project:" and the project name.
> 
> Before: researcher has edited a Project:"Truncated Project Name"
> 
> After: researcher has edited a Project: "Truncated Project Name"
> 
> Other than that, looks good!

ss for actonnotification

**Review by birbjam — APPROVED** [review]

**Pull request merged**
