### PR TITLE
#8688h668p account having count -1

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8688h668p)**

**Description:**
Handle the counts for accounts that has counts -1 and ensure that the count remains constant at -1.

**Solution:**
- Performed Check if the count is -1 then didn't update the count
- Handled Project count, Notification count, User Count, and API key count for institute accounts that has -1 stored in count
- Handled Project count and Notification count for the researcher accounts that has -1 stored in count
 
**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/ac53946c-fea6-4c44-9843-617abf629fa6

### CODE REVIEW

**Review by birbjam — CHANGES_REQUESTED** [review]
Small adjustment request: in the UI, wherever the count is -1, instead of showing the count, can it say `Unlimited` instead?

**Comment by sab-LC** [comment]
> Unlimited



> Small adjustment request: in the UI, wherever the count is -1, instead of showing the count, can it say `Unlimited` instead?

grand(3)
grandfather(2)
grandaccount(1)

**Review by birbjam — APPROVED** [review]
Resolve merge conflicts and this PR is good to go.

**Review by arojas1 — APPROVED** [review]
Looks good! Just a note that the API Key settings already have the count included in the template (with unlimited) so you may need to merge those first before merging this with subscriptions (it should be in the subscriptions branch already)

**Pull request merged**
