### PR TITLE
#8687tx2w0 Added model defination and API end-point for subscription

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8687tx2w0)**
  
**Solution:**
- Created a subscription model with all the necessary fields
- Created an end-point for SF to update HUB once the subscription agreement is signed.
- Moved the valid user_ids from the code to the env file.
- Added date_last_updated field, which will be updated on every change in the model.

**END POINT**
image

**MODEL**
image

### CODE REVIEW

**Comment by birbjam** [comment]
Can you resolve conflicts on this one?

**Comment by sab-LC** [comment]
> Can you resolve conflicts on this one?

conflicts are resolved.

**Comment by birbjam** [comment]
Note to anyone else testing this: You will need to add `export SF_VALID_USER_IDS=` to your env file to clear the error.

**Comment by sab-LC** [comment]
> Looks good, can you also add the new env variable to the example-env files?

sure

**Comment by arojas1** [comment]
Note for later to add helptext to admin panel for counts indicating -1 should be used for unlimited values for staff to be aware of

**Comment by sab-LC** [comment]
> Note for later to add helptext to admin panel for counts indicating -1 should be used for unlimited values for staff to be aware of

image

**Review by lc-hd — APPROVED** [review]

**Pull request merged**
