### PR TITLE
#8688bb00w Researcher account creation subscription form consolidation

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8688bb00w)**

**Description:**
Description is attached in this [ticket](https://app.clickup.com/t/8688bb00w)
**Solution:**
- Updated the researcher creation form and added the subscription forms 
- Updated the connect-researcher template to add recaptcha
- Update the functions to make them general for both researcher and institute.
 
**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/7a89b293-fba8-42c4-a603-02c1d709ac43

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688bb00w Researcher account creation subscription form consolidation](https://app.clickup.com/t/8688bb00w)

**Review by arojas1 — CHANGES_REQUESTED** [review]
I got the same issue as PR #175 
image

**Review by lc-hd — APPROVED** [review]

**Comment by birbjam** [comment]
Screenshot 2024-05-16 at 1 28 17 PM

Same issue here with the tooltip as with the institutions that was adjusted earlier.

**Comment by sab-LC** [comment]
> Screenshot 2024-05-16 at 1 28 17 PM
> 
> Same issue here with the tooltip as with the institutions that was adjusted earlier.

It's resolved now.
image

**Review by birbjam — APPROVED** [review]
Looks good!

**Pull request merged**
