### PR TITLE
#8688bazhf squash institution creation forms

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8688bazhf)**

**Description:**
Description is attached in this [ticket](https://app.clickup.com/t/8688bazhf)
**Solution:**
- Updated ROR Institution creation form to add contact name and contact email.
-  Updated NoROR Institution creation form to add contact name and contact email.
- Updated the views to handle the submission of subscription of institute.
- Updated the templates to render the updated form fields 
- Updated the JS to add the clear form functionality to newly added fields
 
**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/7d642afb-a1bb-436b-abd9-6c06c58a5e9c

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688bazhf Institution account creation subscription form consolidation](https://app.clickup.com/t/8688bazhf)

**Comment by birbjam** [comment]
When testing, went to create a random ROR institution account, filled out all the fields, clicked submit. The button became disabled but the form did not submit. No error messages were shown. 

Screenshot for reference:
Screenshot 2024-05-10 at 9 16 00 AM

**Comment by sab-LC** [comment]
> When testing, went to create a random ROR institution account, filled out all the fields, clicked submit. The button became disabled but the form did not submit. No error messages were shown.
> 
> Screenshot for reference: Screenshot 2024-05-10 at 9 16 00 AM

This was due to no first name and last name and is resolved now

**Review by arojas1 — CHANGES_REQUESTED** [review]
- The Inquiry type tooltip is off the screen would need to adjust to fit within the form's field area:
image
- Inquiry type needs CC Notice Only as an option
- Went to click on submit for a ROR institution and the same issue happened as Diana's comment above, clicked submit and the button went to disabled but still on the same page.
- Tried to test the non-ROR and on submit got this page. Correct me if I am wrong but I think this page should now be bypassed and not accessible to signed up users. That form should only be for Anon Users:
image
- That being said, `is_submitted` and the "Complete Subscription Form" blocking the account card should no longer be needed if the subscription request will be sent on account creation.
- I was thinking we could add a checkbox under description that says something like: **"Will you be the contact person for subscriptions? [ ] Yes [ ] No"**. If yes, contact name and email fields do not have to be shown and we only have to send the user's info. If No, then contact name and email fields can show and we can send an additional contact to SF as the subscription contact

**Comment by birbjam** [comment]
I agree with all of Ashley's comments except for this one:

> I was thinking we could add a checkbox under description that says something like: "Will you be the contact person for subscriptions? [ ] Yes [ ] No". If yes, contact name and email fields do not have to be shown and we only have to send the user's info. If No, then contact name and email fields can show and we can send an additional contact to SF as the subscription contact

I think we should discuss this one because they might not be signing up as a subscriber and this might be confusing for users. Will add to hub standing to discuss.

**Comment by sab-LC** [comment]
> * The Inquiry type tooltip is off the screen would need to adjust to fit within the form's field area:
>   image
> * Inquiry type needs CC Notice Only as an option
> * Went to click on submit for a ROR institution and the same issue happened as Diana's comment above, clicked submit and the button went to disabled but still on the same page.
> * Tried to test the non-ROR and on submit got this page. Correct me if I am wrong but I think this page should now be bypassed and not accessible to signed up users. That form should only be for Anon Users:
>   image
> * That being said, `is_submitted` and the "Complete Subscription Form" blocking the account card should no longer be needed if the subscription request will be sent on account creation.
> * I was thinking we could add a checkbox under description that says something like: **"Will you be the contact person for subscriptions? [ ] Yes [ ] No"**. If yes, contact name and email fields do not have to be shown and we only have to send the user's info. If No, then contact name and email fields can show and we can send an additional contact to SF as the subscription contact

Point 3: I’ve done this in the latest commit. Can you take the fresh pull and then test this point again?
Point 4: This page is there just in case the institution is created and there’s no first or last name of profile or somehow the API call doesn’t work and for these reasons “complete subscription form” and “disabled dashcard” are there to guide the user to submit the SF query correctly.
Point 5: The “is_submitted” field is required, Because the account has just submitted the subscription request and is not subscribed yet, the account will be subscribed once the agreement is signed and a response is received from the SF.

**Comment by sab-LC** [comment]
Added asterisk's to the Subscription Form
asterick

**Review by birbjam — APPROVED** [review]
Looking great!!

**Comment by arojas1** [comment]
> Point 4: This page is there just in case the institution is created and there’s no first or last name of profile or somehow the API call doesn’t work and for these reasons “complete subscription form” and “disabled dashcard” are there to guide the user to submit the SF query correctly.

Should we just require at least first name for profile creation then to avoid this issue? then we can use that to send to SF and not have to have that form show on account creation because it seems out of place now that the inquiry and contact fields have been condense. OR we could send the contact name instead? What do you think @birbjam?

**Review by arojas1 — APPROVED** [review]
Approved for now, just pending further discussions. The only tiny thing I would add is adding "Required" when hovering over astrisks.

**Comment by sab-LC** [comment]
> Approved for now, just pending further discussions. The only tiny thing I would add is adding "Required" when hovering over astrisks.


https://github.com/localcontexts/localcontextshub/assets/145371882/7b033550-ecc5-4cdd-9f22-f0222431bf4c

**Pull request merged**
