### PR TITLE
SP Connections Settings Updated

### PR DESCRIPTION
**Pull request by arojas1**
- Fixed merge issue where some code was not pulled over for the account settings base
- Added functionality for [#8688taugz](https://app.clickup.com/t/8688taugz): SPs can see and manage any accounts that have connected to their account
image
image

- Added Connections count tag [#8688wmxg4](https://app.clickup.com/t/8688wmxg4)
- Added Notices count tag [#86899z2mp](https://app.clickup.com/t/86899z2mp)
- Fixed minor UI bugs for connections card: 
    - Community Name duplicated
    - Buttons not sitting flush on the right side
image

**Will add task to fix location not showing for Researcher cards**

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688taugz SP Account: Connections tab](https://app.clickup.com/t/8688taugz)
Task linked: [CU-8688wmxg4 Add Template Tag: Connections Count](https://app.clickup.com/t/8688wmxg4)

**Comment by arojas1** [comment]
Task linked: [CU-86899z2mp Add Notices Count to SP Dashcard (OTC Notice Links)](https://app.clickup.com/t/86899z2mp)

**Review by lc-hd — APPROVED** [review]

**Review by birbjam — APPROVED** [review]
Looks great! 
One small request: please change the website & documentation icons to filled instead of the ones you used.

**Comment by arojas1** [comment]
Based on feedback, removed Notices count from SP dashcard and updated website and documentaion link icons
image
image

**Pull request merged**
