### PR TITLE
#8688zv1r9 Error when primary institute left empty

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8688zv1r9)**

**Description:**
When attempting to create the researcher account without specifying the primary institution, I get this error " An unexpected error has occurred here. Please contact [support@localcontexts.org](mailto:support@localcontexts.org)."  leading to the creation of the researcher account despite the failed SF call.
image

**Solution:**
- Check if primary institution isn't present than pass researcher's first name to primary institution
- Set isbusiness to False for researcher and True for institution

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688zv1r9 Error when primary institute in /connect-researcher/ left empty](https://app.clickup.com/t/8688zv1r9)

**Comment by birbjam** [comment]
We may need to discuss this because not all researchers are going to be affiliated with an institution necessarily. Will add to hub standing meeting.

**Comment by sab-LC** [comment]
I have included the is business=False for researcher accounts, also have set company_name as first_name for researchers as it is required on SF side(also confirmed using postman)

**Review by lc-hd — APPROVED** [review]
Looks good. Approved!

**Review by birbjam — APPROVED** [review]
Looks good, created a researcher account with a blank primary institution, which created a SF opportunity using first name.

**Pull request merged**
