### PR TITLE
#8687a56n4 community account settings crud boundary

### PR DESCRIPTION
**Pull request by lc-hd**
User can CRUD a community on the account page.

Change Via Native Land Demo

[Change Via Native Land Demo](https://github.com/localcontexts/localcontextshub/assets/145378945/8a33624f-ffa3-44ee-89cd-f9e9fff5b9c5)

---------

Change Via Shapefile Demo

[Change Via Shapefile Demo](https://github.com/localcontexts/localcontextshub/assets/145378945/bea98578-b03f-43fc-8bae-aa0830331d01)

----------------

Attempted Upload With Error

[Attempted Upload With Error](https://github.com/localcontexts/localcontextshub/assets/145378945/38f9719f-b335-48a0-a4b7-cb5457b87071)

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8685cg9uy GIS for Project creation](https://app.clickup.com/t/8685cg9uy)

**Comment by birbjam** [comment]
The task ID for this PR is 8687a56n4

**Review by birbjam — APPROVED** [review]
LGTM!

**Review by arojas1 — CHANGES_REQUESTED** [review]
- Logged into an already existing community with a NLD boundary and when I went to click view location I got an error `Request URL: | http://localhost:8000/helpers/community-boundary-view/1  helpers.views.community_boundary_view`
image
- when trying to remove that same boundary I got this error but then the boundary was removed when I clicked ok.
image
- Error when trying to add a boundary to a brand new community `POST /communities/update-community-boundary-data/7/ HTTP/1.1" 500 108052`
image
- Button says change boundary even when there is no boundary present. Maybe "Update Boundary" would be better?

**Review by arojas1 — CHANGES_REQUESTED** [review]
Thank you for the updates! I was able to test and had the following comments:
- Would it be possible to rename an import? Just thinking of if we move to multiple imports, or if another admin is looking at the settings and they didn't upload this boundary, being able to just see a name would be a quick way to identify what the boundary is without having to click view location. So instead of the example below where it says "geo_export...." I could rename it to "Brooklyn, NY" or something to that effect. Especially if we are going to use those names in other places when showing Community boundaries to the public.
image
- Not sure if this is an NLD issue but I clicked on a specific boundary from the dropdown and got this error:
image
This was the boundary I selected (not sure if other boundaries may have this error but if it doesn't have a boundary, it shouldn't show in the list.
image
- When a boundary is updated or removed from this page, the fields should clear so the previous info isn't still showing
image
- Minor change: the confirmation for file upload should either say "File uploaded successfully" or "File upload successful"
image

**Review by arojas1 — APPROVED** [review]

**Pull request merged**
