### PR TITLE
#8688h60qg Anon User Subscription Form Adjustments

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8688h60qg)**

**Description:**
image

- Remove account type since its not reflected in SF
- Asterisks need to be added to the required fields:
    - First name (confirm this)
    - Email
    - Inquiry Type

For the anon form it should create a lead first, making the organization name optional. If we need to pass something, just pass Unknown.

**Solution:**
- Updated the SubscriptionForm to remove account type in subscription-inquiry view
- Updated the template for subscription-inquiry to include the optional Affiliation's / Organization's form field with the tooltip description of field
- Added asterisk's with the required form fields
- Updated CSS to style the required text as title attribute
 
**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/9f06b8df-73a0-4d40-9d9f-17eeff8ee0e2

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688h60qg Anon User Subscription Form Adjustments](https://app.clickup.com/t/8688h60qg)

**Review by birbjam — APPROVED** [review]
Looking great! Small adjustment request: last field should say `Affiliation(s) or Organization(s)`

**Comment by sab-LC** [comment]
> Affiliation(s) or Organization(s)

image

**Review by arojas1 — APPROVED** [review]
Looks good, but one thing we may need to discuss is having an option at the top of the dropdown list that says something along the lines of name is not in this list so the dropdown can disappear and the typed in affiliation/org can be used. Though when I tried to submit without clicking on anything the form didn't go through properly. But I think the two are related
image

**Pull request merged**
