### PR TITLE
#8688p8yz2 [For Develop] create/edit/view boundary in project for community/institution/researcher

### PR DESCRIPTION
**Pull request by lc-hd**
These are the same changes as this [branch](https://github.com/localcontexts/localcontextshub/pull/210) but it's being merged to the `Develop` branch instead of `Subscriptions` branch.

With these changes, community/institution/researcher accounts will be able to crud a boundary for a project.

-----------------------------

**Create Project**

image

----------------------

**Edit Project**

image

----

**View Project Page**

image

----

**View Project Page Public** (Share Boundrary Publicly =  True)

image

--------------------------

**View Project Page Public** (Share Boundrary Publicly = False)

image

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688p8yz2 Create Project boundary during Project creation](https://app.clickup.com/t/8688p8yz2)

**Review by arojas1 — CHANGES_REQUESTED** [review]
- Added to the next HSM to get some content for the new project section to describe what it is the user can add to that section.
- For NLD boundaries, on the project page, maybe having a title above the map for the boundary with a link directly to that boundary's page so people can see who NLD says it belongs to. Example:
image
With the link going to the NLD's page: https://native-land.ca/maps/territories/lenape/
- For shapefile boundaries, offering the option to name the area in the Project Boundary section so that there is a name to put here indicating what the boundary is referencing.
- For both boundary type, should there be a description section added as well for the person creating the project to detail what land is being covered by the project? Thinking along the lines of a researcher for ex. to explain where the shapefile is encompassing or why the NLD boundary was selected. Or should this just be included in the Description? (if it should be included in the project description, should project boundary be within that project section like project links?)
- The map frame should reach the full width of the div (like in the img above). I added a shapefile that had a small boundary but this is how it rendered on the project page: 
image

**Review by birbjam — DISMISSED** [review]
- Need to discuss the 'share boundary publicly' for Projects, I think it makes sense for communities but not Projects. Will add to hub standing agenda for discussion.
- `Cancel` button should say something like `Clear boundary` instead.

**Comment by lc-hd** [comment]
@arojas1 thanks for the feedback. It has been updated based on your suggestions. I created a subtask for adding the name field. Here's the link: https://app.clickup.com/t/8689039ch

**Comment by lc-hd** [comment]
@birbjam it's been updated. The button has been changed from `Cancel` to `Clear boundary`. This is what it looks like after that change:

image

Also, I'll remove the `share boundary publicly` from the boundary widget based on Hub Standing feeddback

**Review by arojas1 — DISMISSED** [review]
- When clicking on the Name of the boundary on the project view page it took me to the JSON file but it should actually link to the link that is in the description field in the image below:
image
- When I unchecked Share Boundary Publicly and saved, the boundary was still visible on the public project view page.
- @corrieroe is there a sentence and/or tooltip that should be added to this section to explain what is expected for people adding a boundary? (can be a separate PR/task as well if needed)
image

Everything else is looking good!

**Comment by corrieroe** [comment]
> * @corrieroe is there a sentence and/or tooltip that should be added to this section to explain what is expected for people adding a boundary? (can be a separate PR/task as well if needed)
>   image

Yes, can definitely draft a 1-2 sentence description, likely would also suggest helphints.

**Review by birbjam — APPROVED** [review]
I'm going to approve this PR but "share boundary publicly" still needs to be removed here.

**Comment by lc-hd** [comment]
The `share_boundary_publicly` has been removed for projects. Here's a screenshot

image

**Review by arojas1 — APPROVED** [review]
Looks good! I think since you would like to discuss the NLD link description, you should remove the hyperlink for now. You can leave the name of the boundary there but I don't think having it link to the JSON file is a good idea.

**Pull request merged**
