### PR TITLE
#86895xw7x researcher name bug

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8688zphtr)**

**Description:**
Herbert was able to remove both first name and last name from the settings page, which should not have happened as this will create an error in future subscription calls and also the users already present on the HUB may not have a first name and last name and their subscription calls will also generate the same error. The user should not be able to remove the first name and last name from settings as well, Researcher subscription journey should mimic the first name check like institution.
image

**Solution:**
- Updated UserUpdateForm's field first name to required true
- Updated the `connect-researcher/` page to include UserCreateProfileForm for first and last name
- Optimized the helper function for form initiation

**After:**
- **Institution(without first name):**

https://github.com/user-attachments/assets/85d3a6c2-6ed7-4857-b2ad-0dcef47464c1

- **Researcher(without first name):**

https://github.com/user-attachments/assets/14ff97d6-f88c-4d4f-8f70-d16338a9db0b

- **Researcher(with first name):**

https://github.com/user-attachments/assets/b8debffd-d56b-4c4a-9901-fe5e7d089a2d

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-86895xw7x Researcher name bug](https://app.clickup.com/t/86895xw7x)

**Comment by lc-hd** [comment]
Thanks for working on this, I was able to create the same error by bypassing creating the profile and then attempting to create the researcher account. Could we make the error message more specific. Perhaps, the error message could say something such as, "Missing Profile Name"

https://github.com/user-attachments/assets/46445b9a-baf8-4307-bde1-1e678345b8dc

---

image

**Review by lc-hd — CHANGES_REQUESTED** [review]
Thanks for working on this, I was able to create the same error by bypassing creating the profile and then attempting to create the researcher account. Could we make the error message more specific? Perhaps, the error message could say something such as, "Missing Profile Name"

https://github.com/user-attachments/assets/46445b9a-baf8-4307-bde1-1e678345b8dc

---

image

**Comment by sab-LC** [comment]
> Thanks for working on this, I was able to create the same error by bypassing creating the profile and then attempting to create the researcher account. Could we make the error message more specific. Perhaps, the error message could say something such as, "Missing Profile Name"
> 
>  example.mp4 
> image

Have you taken latest pull for the branch ?

**Comment by lc-hd** [comment]
@sab-LC , yes that was on the latest branch. I'll reach out in Slack to demo my experience

**Comment by lc-hd** [comment]
This is working for me now. Approved!

**Review by lc-hd — APPROVED** [review]

**Review by birbjam — APPROVED** [review]

**Pull request merged**
