### PR TITLE
#86896vynq Change Customized Label Behavior

### PR DESCRIPTION
**Pull request by birbjam**
From [this task](https://app.clickup.com/t/86896vynq):
- Removed the preview divs from each customized Label, made the Labels themselves into links that go to the View Label page.
- Updated some UI elements on the View Label page based on what is currently in Figma.
- Adjusted some template logic for which buttons show up for which user.
- Fixed a bug that happened when someone tried to edit an approved Label, which was throwing an error due to the original Label not being set as version 1.

**Before:** 

https://github.com/user-attachments/assets/a6754a68-e975-4965-ad68-9a0fd6381ace

**After:**

https://github.com/user-attachments/assets/f6761f68-2de0-4699-93ff-ffb7673cee74

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-86896vynq Customized Labels: Change behavior for when they are clicked.](https://app.clickup.com/t/86896vynq)

**Review by arojas1 — APPROVED** [review]
Only thing I would add is a placeholder under "Explore your other customized Labels" for when they don't have other customized labels. Something like "No other Labels have been customized yet." Or whatever sounds good.  But other than that this looks gtg.

image

**Comment by birbjam** [comment]
> Only thing I would add is a placeholder under "Explore your other customized Labels" for when they don't have other customized labels. Something like "No other Labels have been customized yet." Or whatever sounds good. But other than that this looks gtg.
> 
> image

Updated:
Screenshot 2024-08-09 at 11 53 57 AM

**Comment by birbjam** [comment]
Will be working with Renee on updating the Label Approval / Label Note UI in a different PR.

**Pull request merged**
