### PR TITLE
#8688gv84u API V2 functionality updates

### PR DESCRIPTION
**Pull request by arojas1**
Updating functionality to include API Keys, filtering calls based on account making the request and subscription status.

- CU-8688620ue: API key helper functions added
- CU-8688hy17a: Project List call updated
- CU-8688hyjby: Added call authentication for SF integration
- CU-8688hycex: Multi-Project Details and Last Updated Date call updated
- CU-8688hyczc: OTC call added profile link
- CU-8688hy8x8: Project Details call updated. Fields added to match Project page GUI
- CU-8688hy9xy: Project List updated to include previous projects by ID calls.
- CU-8688jxpav: API Overview Updated

Note: Update in requirements.txt

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688gv84u Limit API Calls by account via key](https://app.clickup.com/t/8688gv84u)
Task linked: [CU-8688hy17a Project List Call](https://app.clickup.com/t/8688hy17a)
Task linked: [CU-8688hyjby Limit SF Calls to staff only API Key via Developer account](https://app.clickup.com/t/8688hyjby)

**Comment by arojas1** [comment]
Task linked: [CU-8688620ue Move API creation and encryption to helper function](https://app.clickup.com/t/8688620ue)
Task linked: [CU-8688hycex Multi Project List](https://app.clickup.com/t/8688hycex)

**Comment by arojas1** [comment]
Task linked: [CU-8688hyczc Open to Collaborate Notice Call](https://app.clickup.com/t/8688hyczc)

**Comment by arojas1** [comment]
Task linked: [CU-8688hy8x8 Project Details Call](https://app.clickup.com/t/8688hy8x8)

**Comment by arojas1** [comment]
Task linked: [CU-8688hy9xy Project List by ID](https://app.clickup.com/t/8688hy9xy)

**Comment by arojas1** [comment]
Task linked: [CU-8688jxpav API Overview Call](https://app.clickup.com/t/8688jxpav)

**Review by birbjam — APPROVED** [review]
LGTM!

**Review by lc-hd — APPROVED** [review]

**Pull request merged**
