### PR TITLE
#868aa1k24: Add Label and Notice icons higher on Project page

### PR DESCRIPTION
**Pull request by arojas1**
- Icons higher on Project page
- Project metadata moved to details section
- Icons when clicked take user down to Notices or Labels section
- Label icons will wrap to second row if many are added to a project

image
image

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-868ac5c6c Add labels higher on the Project View page](https://app.clickup.com/t/868ac5c6c)

**Comment by arojas1** [comment]
Task linked: [CU-868aa1k24 Add Label/Notice icons to top of project page](https://app.clickup.com/t/868aa1k24)

**Review by lc-hd — APPROVED** [review]
LGTM

**Review by birbjam — APPROVED** [review]
Looks good!

**Pull request merged**
