### PR TITLE
Added label translations on customized label page

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8685r2g00)**
-  This feature is requested by Corrie 
*Feature Name:*  Load Label template text translations 
 Description: If a community selects Māori, French, or Spanish (the languages that have approved LC translations) as the Label language, it would be really cool to auto-load the translated Label template text in that language. This would help communities working in those languages more easily use the template text, rather than going to our website to copy the translations or not knowing those translations exist. 

**Solution:**
- Created LabelTranslation files and customized the _customize-label_ page using JS.

**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/6bb81891-c874-4081-bdfb-149ceaae78b5

### CODE REVIEW

**Review by lc-hd — APPROVED** [review]

**Review by birbjam — COMMENTED** [review]
So this looks great for French, Spanish and Maori but when I try other languages, it replaces the text with "We only support French, Spanish and Maori translations at the moment".

Instead of this, can we have the text and title go back to the default English and have that message appear above the text box? That way the original text is not lost in the switching. Switching back to English does not bring back the text either.

I think it would also be helpful to let the user know somewhere beforehand that we have only these 4 languages available so far.

**Comment by corrieroe** [comment]
Very exciting development!!! Agree with switching the Label text back to English if we do not currently have the translations. Let me know if it would be helpful for me to work on some suggested content for this?

**Comment by birbjam** [comment]
> Very exciting development!!! Agree with switching the Label text back to English if we do not currently have the translations. Let me know if it would be helpful for me to work on some suggested content for this?

That would be great Corrie!

**Comment by arojas1** [comment]
> Very exciting development!!! Agree with switching the Label text back to English if we do not currently have the translations. Let me know if it would be helpful for me to work on some suggested content for this?

Maybe also having a line that says if anyone would like to contribute a translation of the template text to email support?

**Comment by sab-LC** [comment]
https://github.com/localcontexts/localcontextshub/assets/145371882/9e7d3b2c-3619-4cd7-be10-a330f04d1267

@birbjam better?

**Comment by sab-LC** [comment]
> > Very exciting development!!! Agree with switching the Label text back to English if we do not currently have the translations. Let me know if it would be helpful for me to work on some suggested content for this?
> 
> Maybe also having a line that says if anyone would like to contribute a translation of the template text to email support?

Great idea, we can have a discussion on this in one of the team syncs.

**Comment by corrieroe** [comment]
I think you might not need a message if another language is selected, but we can definitely discuss at an upcoming meeting. I'd suggest updating the helphint content:

**Label Language - _helphint content_**
Select the language this Label is written in. English, Māori, French, and Spanish translations of the Label name and template text will be loaded if selected. Can't find the language you are looking for? Contact us at support@localcontexts.org.

**Review by arojas1 — CHANGES_REQUESTED** [review]
Ok so pending @corrieroe's content changes but here are a few things I saw that we may want to discuss/change:
- Having the text prefill in the "Add Label Translations" section for the 4 languages we have would also be helpful.
- I don't think changing the label language back to English for the main language is a good idea because then that requires people to only start with one of the 4 languages we have translated. I think we could leave the Label Language as what they selected, prefill the Label text box with the English and update the notification banner to say something like "We do not have translated Label template text in <SELECTED LANGUAGE> at this time."

**Comment by sab-LC** [comment]
@arojas1 @corrieroe let's discuss this in an upcoming meeting, and will continue on which every body agrees?

**Comment by birbjam** [comment]
> @arojas1 @corrieroe let's discuss this in an upcoming meeting, and will continue on which every body agrees?

Sab, can you add this to the Hub Standing agenda so we can discuss this?

**Comment by sab-LC** [comment]
@arojas1 @birbjam 

https://github.com/localcontexts/localcontextshub/assets/145371882/0ead91e3-936f-4bc9-b0ee-69f1a45a76dc

**Comment by corrieroe** [comment]
**New content for Label language helphint:**
Select the language for this Label. English, Māori, French, and Spanish translations of the Label name and template text will be loaded if selected. Can't find the language you are looking for? Please contact us: support@localcontexts.org.

_When we have a FAQ with more information, we can update this helphint and also add to the "error" message._

**Comment by sab-LC** [comment]
> **New content for Label language helphint:** Select the language for this Label. English, Māori, French, and Spanish translations of the Label name and template text will be loaded if selected. Can't find the language you are looking for? Please contact us: [support@localcontexts.org](mailto:support@localcontexts.org).
> 
> _When we have a FAQ with more information, we can update this helphint and also add to the "error" message._

image (15)

**Review by birbjam — APPROVED** [review]
Looks good to me!

**Review by arojas1 — APPROVED** [review]

**Comment by arojas1** [comment]
Task linked: [CU-8685r2g00 Load Label template text translations if language is selected](https://app.clickup.com/t/8685r2g00)

**Pull request merged**
