### PR TITLE
8686zypwx project visibility of unconfirmed account

### PR DESCRIPTION
**Pull request by lc-hd**
**The user of the confirmed account sees the project:**

image

**The non-user of the unconfirmed account sees a 404:**

image

### CODE REVIEW

**Review by birbjam — APPROVED** [review]
LGTM!

**Review by arojas1 — APPROVED** [review]
LG, just need to remember to either let Outreach know this change is happening so if they get questions they know why that 404 is coming up.

**Comment by birbjam** [comment]
> LG, just need to remember to either let Outreach know this change is happening so if they get questions they know why that 404 is coming up.

I added it as a comment in CU to remind us.

**Comment by arojas1** [comment]
Task linked: [CU-8686zypwx URLs for Projects created by unconfirmed accounts should not be accessible by others](https://app.clickup.com/t/8686zypwx)

**Pull request merged**
