### PR TITLE
#8687c2q86 Added functionality of confirming email change

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8687c2q86)**
  
- Description: Don't think we have anything like this but we should have a confirmation email that is sent to users when their email is changed from their profile (like other platforms do).

This email can either be:
- A confirmation email that a user is sent to the original email letting them know that the email is being changed and an email sent to the new email asking to confirm the email by clicking a button. If not clicked, the email doesnt change in the profile.
- A notification email to the original email saying that their email has been changed and if this was done in error to contact us. No confirmation needed, email changed right away.
- A mix of 1 and 2.

**Solution:**
- Added the functionality of detecting email changes on the update-profile.
- If the new_email doesn't exist in DB, generate a token and send it to new_email.
- Created a view to verify the token from new_email.
- Alert email on old_email notifying the user about the change of email on HUB.
- Made two new templates on Mailgun for new_email and old_email.

**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/708f823d-640a-4f9a-ac7c-b892b2f9ea06

**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/a3e5a69b-982c-4328-a6d3-e73b16850d8a

**Email on New Email:**
email_on_new_email

**Email on Old Email:**
email_on_old_email

### CODE REVIEW

**Comment by arojas1** [comment]
Just tagging @corrieroe to make sure content looks good!

**Comment by corrieroe** [comment]
**Message to new email**

Hello [username],

The email address associated with your Local Contexts Hub user profile was recently changed from [old email] to this email, [new email]. 

Click the button below to verify your email:
Button: Verify email

If you did not make this change or are having issues, please email us at support@localcontexts.org
— Local Contexts Team

**Message to old email**

Hello [username],

The email address associated with your Local Contexts Hub user profile was recently changed from this email, [old email], to [new email]. 

If you made this change, please check your [new email] inbox to verify this email.

If you did not make this change or are having issues, please email us at support@localcontexts.org
— Local Contexts Team

**Review by arojas1 — CHANGES_REQUESTED** [review]
- Got this error when clicking on Verify in the new email, and went to login.
image
- Instead of "You are receiving this email because you updated your email on HUB." maybe change it to "You are receiving this email because you updated your email on URL." - where URL will be either sandbox.localcontexts.org or localcontexts.org so the user knows which location they should be looking at (URL for our develop or localhost would be there instead when testing).

**Comment by arojas1** [comment]
Task linked: [CU-8687c2q86 Add email to have user confirm email change/indicate there was a change in the user's email](https://app.clickup.com/t/8687c2q86)

**Comment by sab-LC** [comment]
> **Message to new email**
> 
> Hello [username],
> 
> The email address associated with your Local Contexts Hub user profile was recently changed from [old email] to this email, [new email].
> 
> Click the button below to verify your email: Button: Verify email
> 
> If you did not make this change or are having issues, please email us at [support@localcontexts.org](mailto:support@localcontexts.org) — Local Contexts Team
> 
> **Message to old email**
> 
> Hello [username],
> 
> The email address associated with your Local Contexts Hub user profile was recently changed from this email, [old email], to [new email].
> 
> If you made this change, please check your [new email] inbox to verify this email.
> 
> If you did not make this change or are having issues, please email us at [support@localcontexts.org](mailto:support@localcontexts.org) — Local Contexts Team

image (19)
image (20)

**Review by birbjam — APPROVED** [review]
Looks and works great, just have a tiny MailGun template change request for the link colors to be the same as the support email:

Screenshot 2024-02-28 at 8 23 24 AM

**Comment by sab-LC** [comment]
> Looks and works great, just have a tiny MailGun template change request for the link colors to be the same as the support email:
> 
> Screenshot 2024-02-28 at 8 23 24 AM
> 
> I also feel like the title of the Alert email for the old email should be changed to something a little more clear. @corrieroe what do you think? Screenshot 2024-02-28 at 8 34 29 AM

Template and email subject is now updated
email_on_old_email

**Comment by birbjam** [comment]
LGTM! Also went thru the registration process and was able to log in successfully after email validation.

**Review by arojas1 — APPROVED** [review]

**Review by lc-hd — APPROVED** [review]

**Pull request merged**
