### PR TITLE
#86888h420 subscription icon

### PR DESCRIPTION
**Pull request by lc-hd**
Subscribed researchers display an orange icon. When one hovers over an icon, a text is display which says subscribed.

---------------

Video Demo1:

https://github.com/localcontexts/localcontextshub/assets/145378945/408dda83-92ee-4f0e-8fc8-1902326e4c84

--------------

Video Demo2: Shows Other Pages

https://github.com/localcontexts/localcontextshub/assets/145378945/7deb9be8-f231-4a56-a0cd-d98545258c7a

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-86888h420 Subscribed and Non Subscribed accounts UI](https://app.clickup.com/t/86888h420)

**Review by sab-LC — APPROVED** [review]

**Review by birbjam — CHANGES_REQUESTED** [review]
Can you update the checkmark to this FA icon: `<i class="fa-sharp fa-solid fa-circle-check"></i>`

Docs for icon sizing: https://docs.fontawesome.com/v5/web/style/size/#_top

The icon should be a little bit smaller than what you currently have.

**Comment by lc-hd** [comment]
This has been updated so the icons are smaller and use the Font Awesome classes for setting the size. Here's are some examples:

------

image



-------

image


-----


image

**Comment by lc-hd** [comment]
This has been updated so it connections for communities/researchers show icons. And researchers, communities, and institutions will show the icons.

https://github.com/localcontexts/localcontextshub/assets/145378945/4c02f4f4-25a9-4da1-8fe3-03edae490ceb

**Review by birbjam — APPROVED** [review]
Made some slight adjustments: added icons to institution connections template and adjusted logic in some of the other templates. 

Otherwise looks good!

**Pull request merged**
