### PR TITLE
Settings Sidebar UI Cleanup

### PR DESCRIPTION
**Pull request by arojas1**
When working on the SP settings I noticed there was a lot of differences across the account and profile settings UI. General updates include the icon alignment and size, and the main content of the settings page being different widths.

Images below (left side is current UI, right side is updated UI)

### **Profile Settings:**
image
image
image
image
image

### **Account Settings:**
Researcher:
image

Community:
image
image

Institution:
image

### CODE REVIEW

**Comment by birbjam** [comment]
Do you have screenshot examples of what this looked like?

**Comment by arojas1** [comment]
@birbjam just updated the main description to include images

**Comment by birbjam** [comment]
Ok I see. The width of content is a bit wide though. In Figma, its more like 75-80% of the card section. 
For example:
Screenshot 2024-08-09 at 12 00 49 PM

Looks good otherwise. Once you made that adjustment, I'll approve.

**Review by lc-hd — APPROVED** [review]
looks good, I do see there are some merge conflicts that need to be resolved

**Review by birbjam — APPROVED** [review]

**Pull request merged**
