### PR TITLE
#8688xv3hn request to join modal bug fix

### PR DESCRIPTION
**Pull request by lc-hd**
## Content Changes: Request To Join Institution

request-to-join-institution

## Clicking Outside Modal Closes Modal
https://github.com/localcontexts/localcontextshub/assets/145378945/83be7b37-306b-463f-a5f3-64f581c95cc0

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688xv3hn Registry: Institution: "Request to join" modal fix](https://app.clickup.com/t/8688xv3hn)

**Review by corrieroe — COMMENTED** [review]
Hi Herbert, content changes are in [this google doc](https://docs.google.com/document/d/1yRV08sDIj5jyAppqKXdSsKQU1ei8alxKkFBvz4TT-zQ/edit#heading=h.3ejg9kthc10z), let me know any questions!

**Comment by birbjam** [comment]
Will approve once content is adjusted but looks good so far.

**Comment by lc-hd** [comment]
This has been updated. Here is what it looks like. @corrieroe I'll reach out on Monday to discuss any tweaks this may need.

-----

To Join Institution
image

----------

To Join Community
image

**Review by birbjam — APPROVED** [review]

**Review by arojas1 — DISMISSED** [review]
Very small change. Would remove the margin left 8 class for the form div so the fields sit flush with the rest of the text.
Before:
image

After:
image

Other than that, looks good!

**Pull request merged**
