### PR TITLE
#8687zzy47 Added subscription settings page

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8687zzy47)**

**Description:**
This should be only available to main admin of the account
The information on the Subscriptions Settings page should be:

 **Subscribed Account:**
- Subscription type: Individual, Small, Medium, Large, CC Notice Only(?)
- Counts of how much of each item is left
  - Projects
  - Users
  - Notifications
  - Notices and Labels
  - API Keys
- Start and end date of the subscription
- Bundle inquiry
  - Select bundle type, then send account id, contact info to which email? (support? subscriptions?)
- Cancellation Inquiry
  - Should this be a link to a form or who to email?
  - Do we have cancellation information available somewhere to link to?

**Unsubscribed account:**
- some information on subscriptions
- link to webform? (or embed webform?)

**Solution:**
- Added a backend view for the subscription view
- Added a template for subscription settings on frontend to display subscription information

**After:**
subscribed-institute
unsubscribed-institute

https://github.com/user-attachments/assets/99353f8b-7050-4e1d-9f19-30d21914d942

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8687xz5z3 Add Webform to Researcher Workflow](https://app.clickup.com/t/8687xz5z3)

**Comment by arojas1** [comment]
Task linked: [CU-8687zzy47 Add Subscriptions Settings Page](https://app.clickup.com/t/8687zzy47)

**Comment by birbjam** [comment]
@sab-LC is this a stale PR? should we close it?

**Review by arojas1 — CHANGES_REQUESTED** [review]
- The `small` tag for all the `p` tags here should be removed. For the little headers for `Start Date`, `End Date`, etc., I would them an `h5` tag. They look too small with the small and h6 tags.
image

- For the Subscription Activity, it should be total remaining/subscription count. For example, the account below has 1 API key created already, but their count for the subscription is 5 keys. So the API key section should say 4/5. `Users Added` should just be Users, same with Projects and Notifications.
image

- When looking at a Researcher account that was not subscribed, I got an error. I think it is looking only at the Subscriptions model but it should be looking for if `is_subscribed` is checked before looking for the subscription information

**Comment by sab-LC** [comment]
> * The `small` tag for all the `p` tags here should be removed. For the little headers for `Start Date`, `End Date`, etc., I would them an `h5` tag. They look too small with the small and h6 tags.
>   image
> * For the Subscription Activity, it should be total remaining/subscription count. For example, the account below has 1 API key created already, but their count for the subscription is 5 keys. So the API key section should say 4/5. `Users Added` should just be Users, same with Projects and Notifications.
>   image
> * When looking at a Researcher account that was not subscribed, I got an error. I think it is looking only at the Subscriptions model but it should be looking for if `is_subscribed` is checked before looking for the subscription information

Ashley, we are not getting the subscription plan info from SF. Once we receive that, we will update our UI to add the total count as well. Already asked rohit for that also

image

**Comment by arojas1** [comment]
> > * For the Subscription Activity, it should be total remaining/subscription count. For example, the account below has 1 API key created already, but their count for the subscription is 5 keys. So the API key section should say 4/5. `Users Added` should just be Users, same with Projects and Notifications.
> 
> Ashley, we are not getting the subscription plan info from SF. Once we receive that, we will update our UI to add the total count as well. Already asked rohit for that also
Maybe the alternative is we only show how many of each count they have remaining? This way we don't need to store 2 different counts and the remaining would be what we have already. I know the figma shows both but showing remaining may be the better option

**Review by arojas1 — CHANGES_REQUESTED** [review]
- Since `EndDate` is not required in the Subscriptions table, the template should handle any accounts that don't have `EndDate` set. At the moment there is an error that shows if `EndDate` is not set.
image
- With how we have the counts at the moment, I would just update the Subscription Activity counts as "Remaining". (Ex: Users Remaining, Projects Remaining, ....etc.). We can always adjust later if needed but for now with this change I think this would be g2g.

**Review by birbjam — APPROVED** [review]

**Pull request merged**
