### PR TITLE
#868885w2v Display Boundary to Public

### PR DESCRIPTION
**Pull request by lc-hd**
Displays a community boundary (if it exists)

https://github.com/localcontexts/localcontextshub/assets/145378945/a31b9fa7-6b1c-4b5d-b9b9-aa5930e24447

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-868885w2v If community has a boundary set, display map on public page](https://app.clickup.com/t/868885w2v)

**Comment by birbjam** [comment]
Can you add a check in the boundary settings for communities that is something like

- [ ] Share boundary publicly

just to give communities the option to not share if they don't want to?

**Review by sab-LC — APPROVED** [review]

**Comment by corrieroe** [comment]
This is exciting to see! I agree with Diana - let's please add an opt-in for public display of community boundary.

**Review by arojas1 — CHANGES_REQUESTED** [review]
I agree with Diana's comment as well. There should be an option for communities to indicate if they would like this boundary shared publicly on the registry.

Also, I think the map should match the figma a bit more if possible with the following additions:
- the map fitting the full width of the page and maybe a bit smaller in height.
- text under the map indicating if the data is coming from NLD or provided as a shapefile (I believe we had mentioned this before in a previous task or meeting so we can use that text)
- date Last Updated that is in this figma would be cool but it would probably be date the settings overall was last updated not just the boundary so that is optional I think but something we should keep in mind later down the line maybe
Screenshot 2024-04-19 at 9 26 00 AM

**Comment by lc-hd** [comment]
> I agree with Diana's comment as well. There should be an option for communities to indicate if they would like this boundary shared publicly on the registry.
> 
> Also, I think the map should match the figma a bit more if possible with the following additions:
> 
> * the map fitting the full width of the page and maybe a bit smaller in height.
> * text under the map indicating if the data is coming from NLD or provided as a shapefile (I believe we had mentioned this before in a previous task or meeting so we can use that text)
> * date Last Updated that is in this figma would be cool but it would probably be date the settings overall was last updated not just the boundary so that is optional I think but something we should keep in mind later down the line maybe
>   Screenshot 2024-04-19 at 9 26 00 AM

Thanks for the feedback Ashley. There is a task for adding NLD or Shapefile annotations to the public page: https://app.clickup.com/t/86884f3tq

**Review by birbjam — APPROVED** [review]

**Pull request merged**
