### PR TITLE
#8688tcw5n fix for suggestion box

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8688tcw5n)**

**Description:**
From Ashley Rojas via Github [conversation](https://github.com/localcontexts/localcontextshub/pull/191#pullrequestreview-2086200180)  
one thing we may need to discuss is having an option at the top of the dropdown list that says something along the lines of name is not in this list so the dropdown can disappear and the typed in affiliation/org can be used.
image

**Solution:**
- Takes the User Input and pass it to showSuggestions() function
- If the User input doesn't match any relevantItems, the User input is shown top of list
- If the User input matches any relevantItems, the User input is replaced by that relevantItem

**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/c816081b-90b0-405a-85cb-eb88487c1f43

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8688tcw5n Fix for the suggestion box in anon subscription form](https://app.clickup.com/t/8688tcw5n)

**Review by arojas1 — APPROVED** [review]
Is it possible for the dropdown to show on top of the frame? just so you dont have to scroll to the bottom of the frame to see all the options.
image
Other than that looks good!

**Comment by sab-LC** [comment]
> Is it possible for the dropdown to show on top of the frame? just so you dont have to scroll to the bottom of the frame to see all the options. image Other than that looks good!

image

**Comment by lc-hd** [comment]
This is what I see on that page. It looks good. Approved

image

**Review by lc-hd — APPROVED** [review]

**Pull request merged**
