### PR TITLE
8685mzfh3 setup oauth

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8685mzfh3)**
  
- Description: Currently the only way to register/login to the Hub is with Django's built-in authentication system that only accepts login with a username and a password. We should setup a way to register/login with Google OAuth.

**Solution:**
To add this whole feature I implemented these steps:
- Added Sign in with Google button on login page and updated login page according to figma.
- Added Register with Google button on register page and updated the page according to figma..
- Added Sign in and Register with google functionality on both login and register pages.
- Added a link-account page in Profile Setting's to connect and disconnect the local account with social account.
- Added the connect and disconnect with Social account functionality.
- Updated Password change form for social and local users
- Added custom message for Google auth user on login 

**Before:**

ouath(1)

oauth(2)

oauth(3)

**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/991fe357-abce-484a-a8a6-25001598faeb

### CODE REVIEW

**Comment by birbjam** [comment]
@sab-LC can you please add `CLIENT_ID` and `CLIENT_SECRET` to the secrets in Passpack?

**Comment by sab-LC** [comment]
> @sab-LC can you please add `CLIENT_ID` and `CLIENT_SECRET` to the secrets in Passpack?

I tried adding them but env-local.sh is only available in (read-only) mode to me.

**Review by lc-hd — APPROVED** [review]

**Review by birbjam — CHANGES_REQUESTED** [review]
- Overall, it looks good but when there's the long error message pushes the sandbox off the main card:
Screenshot 2024-01-22 at 1 59 45 PM

- Update error message to:
`You have already created your account using username and password. Please use those to login instead. You can still connect your account with Google once you login.`

**Comment by arojas1** [comment]
> * Overall, it looks good but when there's the long error message pushes the sandbox off the main card:
>       Screenshot 2024-01-22 at 1 59 45 PM
> 
>     * Update error message to:
>       `You have already created your account using username and password. Please use those to login instead. You can still connect your account with Google once you login.`

Also, maybe move the sandbox callout out out of the div with the Google login button? On the test site and with Renee's figma it takes up more width at the bottom. This should also help with the spacing of that area.
image

**Review by arojas1 — CHANGES_REQUESTED** [review]
- Login button format question sent in figma-questions for Renee's input
- Is there a way to update "localcontexts" to "Local Contexts" and link Privacy Policy and Terms of Service pages from the website in this confirmation box?
image
- When I got the error saying I already signed in, I wanted to try again with another google account but it wouldnt let me try it again.
- Do we need the alert on the dashboard saying you were successfully logged in? I feel like this isn't needed and just cuts up the flow of the page. Signing in normally you don't get an alert so I feel like it isn't needed for GAuth either.
- When Google account is disconnected, user is told to add a password but what is the username? There should either be something that makes them set a username or have the username set as the Gmail and let the user know (example from Canva below)
image

**Comment by sab-LC** [comment]
> * Overall, it looks good but when there's the long error message pushes the sandbox off the main card:
>   Screenshot 2024-01-22 at 1 59 45 PM
> * Update error message to:
>   `You have already created your account using username and password. Please use those to login instead. You can still connect your account with Google once you login.`

- Updated error message and added auto scroll
oauthreview(1)

**Comment by sab-LC** [comment]
> * Login button format question sent in figma-questions for Renee's input
> * Is there a way to update "localcontexts" to "Local Contexts" and link Privacy Policy and Terms of Service pages from the website in this confirmation box?
>   image
> * When I got the error saying I already signed in, I wanted to try again with another google account but it wouldnt let me try it again.
> * Do we need the alert on the dashboard saying you were successfully logged in? I feel like this isn't needed and just cuts up the flow of the page. Signing in normally you don't get an alert so I feel like it isn't needed for GAuth either.
> * When Google account is disconnected, user is told to add a password but what is the username? There should either be something that makes them set a username or have the username set as the Gmail and let the user know (example from Canva below)
>   image

- @arojas1 please have a look.

https://github.com/localcontexts/localcontextshub/assets/145371882/bd6dcd16-d4ae-46a1-bc5a-721a81bc9986

**Comment by sab-LC** [comment]
- Updated modal styling also

image

**Review by arojas1 — CHANGES_REQUESTED** [review]
The other changes look good! The privacy policy should link to [this](https://localcontexts.org/privacy-policy/) page though.

One change I would make would be setting the username for someone who is registering using their google account to be either their full email address or the part before the @. This is because at the moment it just saves the first name of the person's profile (if I'm correct) and there could be multiple people with the same first name. This will then block the account from connecting because the username would already be there (even if it is a different gmail).

**Comment by sab-LC** [comment]
> The other changes look good! The privacy policy should link to [this](https://localcontexts.org/privacy-policy/) page though.
> 
> One change I would make would be setting the username for someone who is registering using their google account to be either their full email address or the part before the @. This is because at the moment it just saves the first name of the person's profile (if I'm correct) and there could be multiple people with the same first name. This will then block the account from connecting because the username would already be there (even if it is a different gmail).

@arojas1 I have updated the privacy policy link. For the users who sign up using their Gmail, the username is decided automatically. for example, I signed up with my email multiple times and every time it gave me a unique username. i.e `sabeen1` `sabeen44` `sabeen3`

**Review by birbjam — APPROVED** [review]
Fixed some minor things: 

Tried on two different browsers but sign-in page looked like this:
Screenshot 2024-01-26 at 3 35 23 PM

After fixing:
Screenshot 2024-01-26 at 3 53 35 PM


Progress bar on register page

**Before:**
Screenshot 2024-01-26 at 3 52 45 PM


**After:**
Screenshot 2024-01-26 at 3 52 57 PM

**Comment by birbjam** [comment]
Otherwise GAuth connecting / disconnecting worked great!

**Review by arojas1 — APPROVED** [review]

**Comment by arojas1** [comment]
Task linked: [CU-8685mzfh3 Set up OAuth with Google to log into the hub](https://app.clickup.com/t/8685mzfh3)

**Pull request merged**
