### PR TITLE
Added subscription type field and updated subscription API

### PR DESCRIPTION
**Pull request by sab-LC**
**Issue:**

**Description:**
The SF payload has included the subscriptions_type in it.This PR is for the adding of subscription_type field in model and Updating the subscription API.

**Solution:**
- Added subscription_type field in model and its migration file
- Updated the API for the subscriptions payload.

**Before:**
image

**After:**
image

### CODE REVIEW

**Review by arojas1 — CHANGES_REQUESTED** [review]
I would also remove Service Providers because now we know their subscription status is going to be processed a bit differently and since they don't have the same count restrictions as other accounts, they won't be getting a subscription object made for them.

Also, we should talk to Subham and see why there are 2 CC Notice fields. There should only be one to avoid confusion.

**Review by birbjam — APPROVED** [review]

**Comment by sab-LC** [comment]
> I would also remove Service Providers because now we know their subscription status is going to be processed a bit differently and since they don't have the same count restrictions as other accounts, they won't be getting a subscription object made for them.
> 
> Also, we should talk to Subham and see why there are 2 CC Notice fields. There should only be one to avoid confusion.

@arojas1 according to Subham these things were set up by Laure

**Review by arojas1 — APPROVED** [review]
> > I would also remove Service Providers because now we know their subscription status is going to be processed a bit differently and since they don't have the same count restrictions as other accounts, they won't be getting a subscription object made for them.
> > Also, we should talk to Subham and see why there are 2 CC Notice fields. There should only be one to avoid confusion.
> 
> @arojas1 according to Subham these things were set up by Laure

Ah okay then, we should ask them to remove the duplicate and then this can be updated. But for now this looks good. In either this PR or a future one we should still remove SP from the Subscription model. Other than that looks good.

**Review by lc-hd — APPROVED** [review]

**Review by birbjam — CHANGES_REQUESTED** [review]
See Slack comment.

**Review by birbjam — APPROVED** [review]

**Pull request merged**
