### PR TITLE
Configured recaptcha enterprise V3

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8687090tx)**
  
- Description: issues with the current reCAPTCHA integration causing users to be unable to register in the develop and staging instances. Need to set up the  reCAPTCHA Enterprise API on all LC-owned instances by updating the secret keys, site keys and updating the two places captcha is used at this time which is on the register page and newsletter-subscription page. 

**Solution:**
- Updated to ReCaptcha Enterprise V3 version.

**After:**

image

**NOTE:**
- ReCaptcha V3 operates on a scoring system, assessing user activity on a scale from 0 to 1. A score of 1 indicates a highly human-like interaction, whereas a score of 0 suggests a more robotic interaction. Currently, I have set a threshold of 0.5.

### CODE REVIEW

**Review by birbjam — APPROVED** [review]
In my never ending quest of accidentally deleting things that were there for a reason, I had to re-create new captcha credentials (and update the site key in templates) so those will need to be updated in secrets when this is merged to develop but otherwise this looks good and works as expected!

**Comment by sab-LC** [comment]
> In my never ending quest of accidentally deleting things that were there for a reason, I had to re-create new captcha credentials (and update the site key in templates) so those will need to be updated in secrets when this is merged to develop but otherwise this looks good and works as expected!

I had created one, but `localcontextshub_v3` is more descriptive and we are good to go with this one.

**Review by lc-hd — APPROVED** [review]

**Review by arojas1 — CHANGES_REQUESTED** [review]
Super minor changes but would just make the check mark for the Privacy Policy and Terms centered.
image

Also would add a space after the last list item and the subscribe button in the newsletter page.
image

**Comment by sab-LC** [comment]
> Super minor changes but would just make the check mark for the Privacy Policy and Terms centered. image
> 
> Also would add a space after the last list item and the subscribe button in the newsletter page. image

image

@arojas1 resolved the first issue, but the newsletter subscription page is fine on my side.

**Review by arojas1 — APPROVED** [review]

**Pull request merged**
