### PR TITLE
Select Boundary via Native Land

### PR DESCRIPTION
**Pull request by lc-hd**
**Happy Path Demo**

This demo represents the typical work flow. You'll notice that before saving the boundaries, the DB tables for boundaries and coordinates are empty. Then after saving, those tables have data.

https://github.com/localcontexts/localcontextshub/assets/145378945/604ea8a3-78f0-4519-86f6-17a8e16dc365

-----------------------

**DB Integrity and Skip to Next Demo**

In this demo, I demonstrated that clicking skip skips all the boundary selection pages and jumps to the confirmation page. Another thing demonstrated is that saving the same boundary twice doesn't cause an accumulation of boundaries and coordinates. Instead, the old boundaries and coordinates are deleted and replaced with new ones. This is done to prevent orphan objects. 
Specifically, boundary 2 is deleted and replaced by 3. Also, coordinates 18-36 were replaced by 37 to 54.

https://github.com/localcontexts/localcontextshub/assets/145378945/b87b6cb5-8531-47cc-9620-f71472107778

----

**Accessing Pages After Community Confirmation Demo**

This demo shows that once a community has been confirmed, one cannot go backwards

https://github.com/localcontexts/localcontextshub/assets/145378945/0e8b754c-3fd2-47d7-91d2-a0fb9af74e88

-----

### CODE REVIEW

**Comment by birbjam** [comment]
This is looking awesome so far!! 
A few requests:

- If the `native_land_slug` is not being used in this contexts, which it looks like it isn't, it should be removed from the Community model (I think there is also a reference to it in the API and a separate call for all the community Native Land slugs so we can remove that).
- I think it would be good for us to be able to see the boundaries for communities when we log into `/admin`.

Otherwise this is looking great, and I appreciate the way those pages are 403ing post-community creation.

**Comment by lc-hd** [comment]
> This is looking awesome so far!! A few requests:
> 
> * If the `native_land_slug` field is not being used in this contexts, which it looks like it isn't, it should be removed from the Community model (I think there is also a reference to it in the API and a separate call for all the community Native Land slugs so we can remove that).
> * I think it would be good for us to be able to see the boundaries for communities when we log into `/admin`.
> * Also from the community creation page, we should remove the city/town, state/province and country inputs as well and only have them as an option if the user does not want to select boundaries nor upload a shape file.
> 
> Otherwise this is looking great, and I appreciate the way those pages are 403ing post-community creation.

Thanks for the feedback. Subtasks have been created for the ability to edit boundaries in the admin panel and modifying the create community page. I'll remove the slug and update the css for the links

**Review by arojas1 — APPROVED** [review]

**Review by birbjam — CHANGES_REQUESTED** [review]
A few small changes requested, the NLD flow looks good!

**Review by sab-LC — APPROVED** [review]

**Review by birbjam — CHANGES_REQUESTED** [review]
- Every boundary I have tried so far has given the alert "Selected Location Does Not Have Any Boundaries", even though when you click on "View Location in NLD" it does have boundaries so I can't go past this step and actually select anything.

Screenshot 2023-12-21 at 2 09 48 PM

- Also I think we should reword the alert a bit as well, saying something along the lines of "Selected location does not have any Native Land boundaries", so it doesn't make it sound like we are saying the boundaries don't exist at all.

**Review by birbjam — APPROVED** [review]
LGTM

**Review by birbjam — APPROVED** [review]

**Comment by arojas1** [comment]
@lc-hd Was testing a different PR and noticed a minor thing that should be updated for this feature. Would you be able to have the dropdown for the NLD boundary search auto show the related items after the user types in at least 3 letters? Atm you have to click "Enter" for the dropdown to show any related results. The magnifying glass also doesn't click to show the results.
image

**Pull request merged**
