### PR TITLE
#8689e4kkg name field additional changes

### PR DESCRIPTION
**Pull request by lc-hd**
**Demo on the Edit Project Boundary Page:**

https://github.com/user-attachments/assets/ced03ccf-02e5-4197-8909-0f55c953955b

---------

**Demo on the Edit Community Boundary Page:**

https://github.com/user-attachments/assets/d2ea019a-3faf-41cd-b30d-1f27577cc5d1

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-8689e4kkg Additional Changes to Shapefile Name Field](https://app.clickup.com/t/8689e4kkg)

**Review by birbjam — DISMISSED** [review]
Can you make the edit icon smaller and make the color of it match the text? Adding the class `sm` to the icon should size it down.

**Comment by lc-hd** [comment]
> Can you make the edit icon smaller and make the color of it match the text? Adding the class `sm` to the icon should size it down.

I have a question on the color. I'll reach out in Slack

**Comment by lc-hd** [comment]
**Community Settings Boundary**

https://github.com/user-attachments/assets/729e188b-8ea6-420e-8e51-c23ef224303c


------


**Community Project Boundary**

https://github.com/user-attachments/assets/3069f622-956e-4e8c-8e5d-285c03f0c256

**Review by birbjam — APPROVED** [review]
Made a very slight adjustment to the text around the Project boundary but otherwise looks good to go.

**Review by arojas1 — APPROVED** [review]

**Pull request merged**
