### PR TITLE
#868746e8t Content Update

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/868746e8t)**

**Description:**
From @ar8117 via [Slack message](https://localcontexts.slack.com/archives/C05SU5R08R1/p1706042492.214079)
In prep for subscriptions (minor edit) this error message should be something along the lines of "This institution is already on the Hub to join that account click here." It should also be at the top of this section instead of having to scroll to the bottom (will add this to CU)

**Solution:**
- Updated ```main.js``` to remove the error 
- Updated the ```create-custom-institution.html``` and ```create-institution.html``` template to move the error message upwards

**Before:**
image

**After:**

create(ror)
create(noror)

### CODE REVIEW

**Comment by arojas1** [comment]
Task linked: [CU-868746e8t Content Update: User trying to create Insitution that is already in the Hub error msg](https://app.clickup.com/t/868746e8t)

**Review by arojas1 — CHANGES_REQUESTED** [review]
Can the error message content be changed as well to be something along the lines of "This institution is already on the Hub."

**Comment by sab-LC** [comment]
> Can the error message content be changed as well to be something along the lines of "This institution is already on the Hub."

content(feedabck)

**Review by birbjam — APPROVED** [review]

**Review by arojas1 — APPROVED** [review]
That's fine, I meant more along the lines of the whole error message being that text instead of having the field name shown. But it is okay for now. It just looks weird having the error message indicate the field it is having an issue with on the user side

**Pull request merged**
